import "~/styles/globals.css";

import { type Metadata } from "next";
import {
  ClerkProvider,
  OrganizationSwitcher,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Geist } from "next/font/google";
import { TRPCReactProvider } from "~/trpc/react";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Tooltracker",
  description: "Generated by create-t3-app",
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={geist.variable}>
      <body>
        <style>{`
          body {
            margin: 0;
            font-family: var(--font-geist-sans), system-ui, sans-serif;
            background: #f3f4f6;
            color: #111827;
          }

          .header {
            display: flex;
            align-items: center;
            gap: 16px;
            height: 64px;
            padding: 0 16px;
            border-bottom: 1px solid #e5e7eb;
            background: #ffffff;
          }

          .link {
            font-size: 14px;
            color: #2563eb;
            text-decoration: none;
            font-weight: 500;
          }

          .link:hover {
            text-decoration: underline;
          }

          .signupBtn {
            height: 40px;
            padding: 0 16px;
            border-radius: 999px;
            border: none;
            background: #6c47ff;
            color: #ffffff;
            font-size: 14px;
            font-weight: 500;
            cursor: pointer;
          }

          .signupBtn:hover {
            opacity: 0.9;
          }
        `}</style>

        <ClerkProvider>
          <TRPCReactProvider>
            <header className="header">
              <SignedOut>
                <SignInButton />
                <SignUpButton>
                  <button className="signupBtn">Sign Up</button>
                </SignUpButton>
              </SignedOut>

              <SignedIn>
                <OrganizationSwitcher />
                <UserButton />
                <Link href="/" className="link">
                  Home
                </Link>
                <Link href="/create" className="link">
                  Opprett blad
                </Link>
                <Link href="/settings" className="link">
                  Innstillinger
                </Link>
              </SignedIn>
            </header>

            {children}
          </TRPCReactProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
