// app/layout.tsx
import "~/styles/globals.css";
import { type Metadata } from "next";
import { ClerkProvider, SignedIn } from "@clerk/nextjs";
import { Geist } from "next/font/google";
import { TRPCReactProvider } from "~/trpc/react";

import HeaderComponent from "./_components/layout/HeaderComponent";
import OrgGate from "./_components/orgGate";
import { OrgChangeListener } from "./_components/OrgWatcher";

export const metadata: Metadata = {
  title: "Tooltracker",
  description: "Generated by create-t3-app",
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={geist.variable}>
      <body>
        <ClerkProvider>
          <TRPCReactProvider>
            {/* 1) Låser signed-in uten org -> /select-org */}
            <OrgGate />
            <OrgChangeListener />

            {/* 2) Låser signed-out visuelt (dekker ALT) */}

            {/* 3) Header vises kun når innlogget (OrgGate sørger for org) */}
            <SignedIn>
              <HeaderComponent />
            </SignedIn>

            {children}
          </TRPCReactProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
