import "~/styles/globals.css";
import HeaderComponent from "../app/_components/layout/HeaderComponent";

import { type Metadata } from "next";
import {
  ClerkProvider,
  OrganizationSwitcher,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Geist } from "next/font/google";
import { TRPCReactProvider } from "~/trpc/react";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Tooltracker",
  description: "Generated by create-t3-app",
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={geist.variable}>
      <body>
        <ClerkProvider>
          <TRPCReactProvider>
            <header className="header">
              <HeaderComponent />
            </header>

            {children}
          </TRPCReactProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
